---
- name: Disable NetworkManager
  service: name=NetworkManager enabled=no

- name: Enable systemd-networkd
  service: name=systemd-networkd enabled=yes

- name: Enable systemd-resolved
  service: name=systemd-resolved enabled=yes

- name: Create systemd-network dir
  file: >
    path=/etc/systemd/network
    state=directory

- name: Create static IP configuration
  template: >
    src=templates/kvm_network.j2
    dest=/etc/systemd/network/ens.network
    owner=root
    group=root
    mode=0644

- name: Create resolv.conf symlink
  file: >
    src=/run/systemd/resolve/resolv.conf
    owner=root
    group=root
    dest=/etc/resolv.conf
    force=yes
    state=link

- name: Set hostname
  hostname: name={{ linux_box.hostname }}

- name: Reboot and wait till box is up with networkd and resolved
  shell: 'sleep 2 && shutdown -r now'
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for box is alive
  local_action: >
    wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
